production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    min_memory: 64M
    max_memory: 128M
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development
    # min_memory: 64M
    # max_memory: 128M

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    